### Feature Refund — CREATE

POST http://localhost:4000/api/reembolsos
Content-Type: application/json
# @name createRefund

{
  "amount": 50000,
  "reason": "El proyecto no alcanzó la meta de financiación",
  "refund_date": "2026-09-29",
  "contribution_id": 1,
  "status": "active"
}
