### Feature Reward — GET ALL / GET ONE
### Leyenda: SIN AUTH (sin middleware JWT / sin autenticación)
@baseUrl = http://localhost:4000
@id = 1

# @name getAllRewards
GET {{baseUrl}}/api/recompensas

###

# @name getOneReward
GET {{baseUrl}}/api/recompensas/{{id}}
