### Feature Disbursement — DELETE

DELETE http://localhost:4000/api/desembolsos/1
# @name deleteDisbursementPhysical

###

PATCH http://localhost:4000/api/desembolsos/1/deactivate
# @name deleteDisbursementLogical
