### Feature Disbursement — DELETE

DELETE http://localhost:4000/api/desembolsos/1/fisico
# @name deleteDisbursementPhysical

###

PATCH http://localhost:4000/api/desembolsos/1/logico
# @name deleteDisbursementLogical
