### Feature Commission — DELETE

DELETE http://localhost:4000/api/comisiones/1
# @name deleteCommissionPhysical

###

PATCH http://localhost:4000/api/comisiones/1/deactivate
# @name deleteCommissionLogical
