### Feature PaymentTransaction — CREATE

POST http://localhost:4000/api/transacciones-pago
Content-Type: application/json
# @name createPaymentTransaction

{
  "reference": "TRX-0001",
  "payment_method": "tarjeta_credito",
  "amount": 50000,
  "transaction_date": "2026-09-29",
  "contribution_id": 1,
  "status": "active"
}
