### Feature PaymentTransaction — DELETE

DELETE http://localhost:4000/api/transacciones-pago/1
# @name deletePaymentTransactionPhysical

###

PATCH http://localhost:4000/api/transacciones-pago/1/deactivate
# @name deletePaymentTransactionLogical
